### ISSUE TITLE
"Idling..." falsely printed

### ISSUE THREAD

**Issue by JesseSilverberg** [mclumd/alma-2.0#2]
When all preconditions are met for a `proc`, alma will print `Idling...` even though if it gets stepped again, it will make a new conclusion from the `proc`.

Example:
`fif(and(hearing(julia),proc(learned(not(talking),A),bound)),conclusion(ros(speak()))).`

**Comment by goldburger** [comment]
Fixed in https://github.com/mclumd/alma-2.0/commit/979870f49b9ccae55cf664ec2a71cfd6a5102941

Note that proc behavior in fif has changed as part of idling correction -- a given proc clause (that isn't the first arg for its enclosing fif) is attempted only once after each preceding literal unifies in that fif.
